export const SET_CLIENT_KEY = 'SET_CLIENT_KEY';

export const REQUEST_STATIONS = 'REQUEST_STATIONS';
export const RECEIVE_STATIONS = 'RECEIVE_STATIONS';
export const RECEIVE_STATION = 'RECEIVE_STATION';
export const STATION_ERROR = 'STATION_ERROR';